### ISSUE TITLE
Running Error?

### ISSUE THREAD

**Issue by cszy98** [ace19-dev/gvcnn#5]
After preparing for the modelnet40, there is an error when running the code:

totalMemory: 10.91GiB freeMemory: 10.34GiB
2019-04-22 10:37:55.656508: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-04-22 10:37:55.782679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-22 10:37:55.782723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-04-22 10:37:55.782730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-04-22 10:37:55.782912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9995 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)

 Epoch 0 

2019-04-22 10:38:30.294264: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.299554: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.308661: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.314694: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.319719: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.332460: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.338507: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.346839: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.350631: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.366402: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.370935: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.378067: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.386358: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.392612: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.397588: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.407753: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.416823: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.430087: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.439906: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.450038: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.454743: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
2019-04-22 10:38:30.460643: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/encoded.  Can't parse serialized Example.
Traceback (most recent call last):
  File "/home/arcwoc/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/arcwoc/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/arcwoc/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: image/encoded.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}} = ParseSingleExample[Tdense=[DT_STRING, DT_INT64], dense_keys=["image/encoded", "image/label"], dense_shapes=[[8], []], num_sparse=0, sparse_keys=[], sparse_types=[]](arg0, ParseSingleExample/Const, ParseSingleExample/Const_1)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,8,299,299,3], [?]], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

I have followed the steps in the ReadMe, but i do not know how this happens and i am looking forward for your solution, thanks a lot!

**Comment by ace19-dev** [comment]
Hi Arcwoc

could you please check .md file and .py files again.
i edited contents more detail

i think you didn't make correct tfrecord file with its corresponding dataset.

thanks for your interest.
